[LIB-254] Properly work with seconds
projecthamster/hamster-lib pull request #237
Opened 2017-07-04 16:03 UTC by elbenfreund

Previous versions of ``hamster-lib`` tried to be overly accomodating by
omitting seconds when parsing/displaying a times. This caused various
bugs and inconsistencies and is fixed by this commit.
While future versions may provide additional liberalizations our
solution now is the most accurate and strict one. It will be easier to
relax things on top of this than the other way round.

Please note that this also means that 'raw fact' parsing now requires
times to be specified as ``%H:%M:%S``

Closes: [LIB-254](https://projecthamster.atlassian.net/browse/LIB-254)

2017-07-04 16:54 UTC, jtojnar commented
I am not very comfortable with raw fact requiring seconds.

2017-07-04 17:24 UTC, elbenfreund commented
Well, then we will need to come up with a new feature PR that introduces liberalizations for raw fact time parsing :)

2017-07-05 13:43 UTC, elbenfreund commented
rdy

2017-07-14 16:21 UTC, elbenfreund commented
@jtojnar Please have a look if you find the time :)

2017-07-15 20:25 UTC, jtojnar requested changes

2017-07-15 20:25 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +    time_pattern = '((?P<time>\d{2}:\d{2})|(?P<time>\d{2}:\d{2}:\d{2}))'
We should probably check how regexes work:

```ipython
>>> regex.match('((?P<time>\d{2}:\d{2})|(?P<time>\d{2}:\d{2}:\d{2}))', '12:00:00').groupdict()
{'time': '12:00'}
```

Something like `(?P<time>\d{2}:\d{2}(?::\d{2})?)` will probably work better.

2017-07-15 20:25 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +    datetime_pattern = ('((?P<datetime>\d{4}-\d{2}-\d{2} \d{2}:\d{2})|'
Same here.

2017-07-15 20:25 UTC, jtojnar commented on setup.py
> +    'regex',
After simplification of regexes, `re` should suffice.

2017-07-15 20:25 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +            try:
If we name the seconds group, we can decide parsing method without try-except. Alternately, we can switch based on time string length.

2017-07-19 15:39 UTC, elbenfreund commented on setup.py
> +    'regex',
sadly, it does not seem to... :/

2017-07-19 15:39 UTC, elbenfreund commented
ready again

2017-07-19 15:57 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +            time = get_time(groupdict.get('time'), seconds=groupdict.get('seconds'))
Why do you name the argument?

2017-07-19 15:57 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +    datetime_pattern = ('(?P<datetime>\d{4}-\d{2}-\d{2} \d{2}:\d{2}(:\d{2})?)')
Forgotten parentheses around the string.

2017-07-19 16:10 UTC, elbenfreund commented
are you sure?

(btw: can't find this comment on the web interface)

2017-07-19 16:20 UTC, elbenfreund commented
rdy :)

2017-07-19 16:22 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +    datetime_pattern = ('(?P<datetime>\d{4}-\d{2}-\d{2} \d{2}:\d{2}(:\d{2})?)')
Yes, the parentheses were used for string concatenation. Since there is only one string now, they are not needed.

2017-07-19 16:24 UTC, elbenfreund commented on hamster_lib/helpers/time.py
> +    datetime_pattern = ('(?P<datetime>\d{4}-\d{2}-\d{2} \d{2}:\d{2}(:\d{2})?)')
ah. ofc. I thought you meant that there were parentheses missing ...

2017-07-19 16:29 UTC, jtojnar requested changes

2017-07-19 16:29 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +    time_pattern = '(?P<time>\d{2}:\d{2}(?<seconds>:\d{2})?)'
Missing `P` in `?<seconds>`.

2017-07-19 16:30 UTC, jtojnar commented on setup.py
> +    'regex',
What is it needed for now?

2017-07-19 16:40 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +import re
is this correct isort position?

2017-07-19 16:43 UTC, jtojnar commented on hamster_lib/helpers/time.py
> +import re
I guess not, according to travis.

2017-07-20 14:34 UTC, jtojnar commented on hamster_lib/helpers/time.py
>              date = get_date(groupdict.get('date', None))
Why do you keep the default_value argument here but remove it on the next line?

2017-07-20 14:38 UTC, jtojnar approved these changes

2017-08-07 15:15 UTC, merged

2018-09-01 22:12 UTC, ederag commented
Does it mean that hamster-lib format is not compatible with the original hamster.db ?

2018-11-21 08:41 UTC, elbenfreund commented
@ederag yes, is is not. However, for far more severe reasons than those discussed here. Multiple conscious design decision early on in the process meant that we will have to break simple compability with the old ``hamster.db``. The biggest being the fact that we do not allow facts to have nullable end datetimes.

**however** we will provide a migration path and idealy even convenience "wizzard" like dialogue that will provide the ability to "import" existing data into the new database. However, because the new semantics are stricter, there will be facts (that have no end) that we will not be able to import without some kind of conflict resolution by the user.

2018-11-26 20:13 UTC, ederag commented
@elbenfreund  forbidding facts with no end-time except for the last one makes sense.
So this design choice seems very good to me.
But it does not seem so important because stats were wrong in that case in legacy hamster,
so it would only happen by mistake, hence rarely.
Anyway, it would be relatively easy for a user to fix the old database prior to upgrade.
(obviously an import wizard would be even nicer)

Once fixed, it would even be possible to use the same database with both versions,
if it were the only "incompatibility".

So this is a huge change (for the better), but perhaps not the worst incompatibility ?

2018-11-27 11:05 UTC, ederag commented
@elbenfreund  forbidding facts with no end-time except for the last one makes sense.
So this design choice seems very good to me.
But it does not seem so important because stats were wrong in that case in legacy hamster,
so it would only happen by mistake, hence rarely.
Anyway, it would be relatively easy for a user to fix the old database prior to upgrade.
(obviously an import wizard would be even nicer)

Once fixed, it would even be possible to use the same database with both versions,
if it were the only "incompatibility".

So this is an important change (for the better), but perhaps not the worst incompatibility ?